### PR TITLE
Make Intercom thread safe

### PR DESCRIPTION
**Pull request by tscolari**
Removed the instance variables on modules, that would be shared between different threads, by the `Thread.current` hash.

Currently on driftrock.com our use case requires us to switch intercom credentials on each request, this changes will make it possible for apps using thread servers (e.g. puma) to safely switch their intercom credentials.

A best approach in my opinion would instead of a module, `Intercom` be a proper class and get instantiated (it's already a module with state anyway), but that would be a breaking change.

### CODE REVIEW

**Comment by scpike** [comment]
@josler any progress here? I just set up intercom and I'm seeing an average response time of ~187ms for the event API, so I'd like to run the create inside a thread.  I'm not changing anything about the  Intercom configuration at runtime, so maybe it's safe as is?

**Comment by josler** [comment]
No news to share about this currently. For your use case it should be fine if you're not switching credentials between threads.

**Comment by josler** [comment]
https://github.com/intercom/intercom-ruby/pull/159 - this is a WIP beta of v3 of this client, which does not have global credentials

**Comment by josler** [comment]
This is implemented now! :tada:

**Pull request closed without merging**
