### PR TITLE
version 3 - client based intercom ruby

### PR DESCRIPTION
**Pull request by josler**
```ruby
client = Intercom::Client.new(app_id: 'app_id', api_key: 'api_key')

# find user by email
user = client.users.find(email: 'test1@example.com')
puts user.email

# loop over all users
client.users.all.each do |user|
  puts user.email
end

# save existing
user.user_id = "77bnh4"
client.users.save(user)

# create new, then delete (2 requests)
u = client.users.create( user_id: 'doodoo' )
client.users.delete(u)
```

### CODE REVIEW

**Comment by josler** [comment]
contacts:

```ruby
contact = client.contacts.find(id: "63g78ac87ec4")
new_user = client.contacts.convert(contact, user)
```

**Comment by josler** [comment]
```ruby
puts client.rate_limit_details
# {:limit=>500, :remaining=>500, :reset_at=>2015-05-28 16:00:00 +0100}
```

**Comment by josler** [comment]
admins:

```ruby
admin = client.admins.all.each { |a| puts a.name }
```

companies:

```ruby
client.companies.find(id: "abc6123def87")

#users in company
client.companies.users("abc6123def87").each do { |u| puts u.id }
```

**Comment by josler** [comment]
subscriptions:

```ruby
client.subscriptions.create(:url => "http://example.com", :topics => ["user.created"])
subscription = client.subscriptions.find(:id => "nsub_123456789")
```

events:

```ruby
client.events.create(:event_name => "item_sold", :email => 'joe@example.com')
```

**Comment by josler** [comment]
messages:

```ruby
client.messages.create(:from => { :type => "user", :email => "jim@example.com" }, :body => "halp")
```

notes:

```ruby
client.notes.create("body" => "Note to leave on user"
client.notes.find(id: '123')
```

**Comment by josler** [comment]
tags:

```ruby
client.tags.tag(:name => "Test Tag", :user_ids => ["abc123", "def456"])
client.tags.untag(:name => "Test Tag", :user_ids => ["abc123", "def456"])
```

users by tag:

```ruby
client.users.by_tag(124).each { |u| puts u.email  }
```

**Comment by josler** [comment]
segments:

```ruby
client.segments.all.to_a
```

users by segment:

```ruby
client.users.by_segment('55490e308a6818289f000007').each { |u| puts u.email }
```

**Comment by josler** [comment]
conversations:

```ruby
client.conversations.mark_read('157')
client.conversations.reply(id: '157', type: 'user', body: 'Thanks again', message_type: 'comment', intercom_id: '55390fd78a6818acb1000099')
```

**Comment by brandonweiss** [comment]
Nice! If 1.9.3 support is being dropped perhaps some named parameters would be nice? E.g.

```ruby
Intercom::Client.new(app_id: 'my_app_id', api_key: 'my_api_key')
```

**Comment by josler** [comment]
:+1:  done

**Comment by gaffneyc** [comment]
This is all really interesting but I am having trouble understanding what necessitated this change or what the benefits our. Is there a rationale somewhere or list of issues we may run into if we stay on version 2?

**Comment by josler** [comment]
@gaffneyc - this change lets you use Intercom in a multi-app environment. For example, if you're providing an integration with Intercom to your own customers, creating `client` objects to interact with Intercom's API with different permission sets is much better that swizzling global settings under `Intercom::`.

New functionality as it arrives will be going into v3 though we're committed to not making breaking changes to our API that would affect v2 (or any client) going forward.

**Comment by gaffneyc** [comment]
@josler thanks for the response. That makes sense, though it's not a use case we're likely to run into only managing a single application.

**Pull request merged**
