### PR TITLE
CI against Ruby 2.4

### PR DESCRIPTION
**Pull request by pocke**
- Add Ruby 2.4.2 to CI matrix
- Update other versions to latest

### CODE REVIEW

**Comment by pocke** [comment]
And I added Ruby 2.5.0 to the matrix.

**Comment by theandrewykim** [comment]
Hey @pocke ! Just wanted to let you know that I haven't forgotten about this PR- I'm just not too familiar with CI, so looking into this one.

**Comment by swistak35** [comment]
Is there a plan to merge this ruby 2.4 support? It's green on travis, so are there any objections not to merge this?

**Comment by jonnyom** [comment]
Hey @pocke as we've moved to Circle for our CI, this PR is no longer relevant so I'm going to close it out.

Happy to chat further 👍

**Pull request closed without merging**
