### PR TITLE
Support find_all for Events

### PR DESCRIPTION
**Pull request by reidab**
Per https://developers.intercom.io/reference#list-user-events

### CODE REVIEW

**Comment by flood4life** [comment]
@reidab 
This will raise really weird errors if event's metadata has key `type`, because deserializer will think that it's a special hash, like `"type" => "event.list"`

**Comment by reidab** [comment]
I'm not sure if special-casing `metadata` like this has unintended consequences, but it seems fairly safe to me. What do you think?

**Comment by flood4life** [comment]
@reidab I had to implement same functionality, and spent a few hours trying to figure out where do such errors come from, so I'm pretty sure that this `metadata` has unintended consequences :)
Examples of errors: `(eval):7: syntax error, unexpected tIDENTIFIER, expecting keyword_end`, `NoMethodError: undefined method `end_with?' for 0:Fixnum`, `NameError: wrong constant name Name with whitespace` 
This is pretty safe, in fact, I've fixed this behavior in absolutely the same way, and the SDK works totally fine for several weeks now.

**Comment by Skaelv** [comment]
Hey @reidab that's very cool! Thanks.
I think you are right to use `find_all` it makes sense.
I was thinking of using `find` but we should definitely go with your implementation. 

 
Can you fix the conflicts with `spec/spec_helper.rb` and take a look at my PR : https://github.com/intercom/intercom-ruby/pull/286/files and update the readme according to it. 
(replace `find` to `find_all`)

 
+ I wanted to add the event summary list : 

In `spec/spec_helper.rb`
```ruby 
def test_events_summary_list
  {
    :email => "dummy@intercom.io",
    :events => [{"name"=>"hamster_catcher", "first"=>"2015-07-02T17:20:22.000Z", "last"=>"2015-07-02T17:20:22.000Z", "count"=>1, "description"=>nil},
      {"name"=>"invited-friend", "first"=>"2016-09-19T09:18:56.000Z", "last"=>"2016-09-19T09:21:15.000Z", "count"=>2, "description"=>nil}
    ],
    :intercom_user_id=> "5591b8d40f8244a7c3000b2c",
    :user_id => "446"
  }
end
```

and in `spec/unit/intercom/event_spec.rb`: 
```ruby
it "fetches a user's events summary list" do
      client.expects(:get).with("/events", {"type" => "user", "intercom_user_id" => "123abc", "summary" => "true"}).returns(test_events_summary_list)
      events = client.events.find("type" => "user", "intercom_user_id" => "123abc", "summary" => "true")
      events.events[1]["name"].must_equal "invited-friend"
      events.events[1]["count"].must_equal 2
    end
```

If you want to add it at the same time that would be great. If you don't have time let me do it after we merged your PR.

**Comment by Skaelv** [comment]
https://github.com/intercom/intercom-ruby/pull/299
Thks @reidab 👍

**Pull request closed without merging**
